// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxvewyrxnimxrartklqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4dmV3eXJ4bmlteHJhcnRrbHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTc2ODIsImV4cCI6MjA2MjI5MzY4Mn0.RQeI22tVcBx6WoRcp2b8CbWu8d20dbYznVT-cuNhyss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);